tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "arp-scan"
brew "python@3.9"
brew "awscli"
brew "docker", link: false
brew "glib"
brew "krb5"
brew "ruby"
brew "macvim"
brew "mysql@5.7", restart_service: true
brew "nodebrew"
brew "nvm"
brew "postgresql", restart_service: true
brew "python@3.8"
brew "ruby-build"
brew "rbenv"
brew "yarn"
cask "android-studio"
cask "appcleaner"
cask "brave-browser"
cask "discord"
cask "docker"
cask "intellij-idea"
cask "intellij-idea-ce"
cask "iterm2"
cask "musescore"
cask "postman"
cask "proxyman"
cask "raspberry-pi-imager"
cask "sequel-ace"
cask "typora"
cask "visual-studio-code"
cask "workflowy"
cask "zeplin"
